# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"NeedUpdateIndex": "database.ipynb",
         "Database": "database.ipynb",
         "DatabaseHelper": "helper.ipynb",
         "Querier": "query.ipynb",
         "DatabaseS3": "s3.ipynb",
         "Updater": "update.ipynb"}

modules = ["database.py",
           "helper.py",
           "query.py",
           "s3.py",
           "update.py"]

doc_url = "https://thanakijwanavit.github.io/villaProductDatabase/"

git_url = "https://github.com/thanakijwanavit/villaProductDatabase/tree/master/"

def custom_doc_links(name): return None
