# AUTOGENERATED! DO NOT EDIT! File to edit: Helpers.ipynb (unless otherwise specified).

__all__ = ['Helpers', 'notify', 'keys']

# Cell
from nicHelper.wrappers import add_method, add_class_method, add_static_method
from linesdk.linesdk import Line
import os



# Cell
class Helpers:
  pass

# Cell
@add_static_method(Helpers)
def notify(message):
  line = Line(os.environ.get('LINEKEY'))
  r = line.sendNotify(message)
  if r.status_code != 200:
    print(r.json())
    return False
  return True

# Cell
@add_class_method(Helpers)
def keys(cls):
  keys = list(vars(cls)['_attributes'].keys())
  return keys